#ifndef SMTPCLIENTERRORS_H
#define SMTPCLIENTERRORS_H

// Authenticate error codes
const int CLIENT_AUTHENTICATE_ERROR = -81;
const int CLIENT_AUTHENTICATE_TIMEOUT = -82;
const int CLIENT_AUTHENTICATE_NONEED = -83;
const int CLIENT_AUTHENTICATION_METHOD_NOTSUPPORTED = -84;

// Send Mail error codes
const int CLIENT_SENDMAIL_MAILFROM_ERROR = -85;
const int CLIENT_SENDMAIL_MAILFROM_TIMEOUT = -86;
const int CLIENT_SENDMAIL_RCPTTO_ERROR = -87;
const int CLIENT_SENDMAIL_RCPTTO_TIMEOUT = -88;
const int CLIENT_SENDMAIL_DATA_ERROR = -89;
const int CLIENT_SENDMAIL_DATA_TIMEOUT = -90;
const int CLIENT_SENDMAIL_HEADERFROM_ERROR = -91;
const int CLIENT_SENDMAIL_HEADERTOANDCC_ERROR = -92;
const int CLIENT_SENDMAIL_HEADERSUBJECT_ERROR = -93;
const int CLIENT_SENDMAIL_HEADERCONTENTTYPE_ERROR = -94;
const int CLIENT_SENDMAIL_BODYPART_ERROR = -95;
const int CLIENT_SENDMAIL_BODY_ERROR = -96;
const int CLIENT_SENDMAIL_END_DATA_ERROR = -97;
const int CLIENT_SENDMAIL_END_DATA_TIMEOUT = -98;
const int CLIENT_SENDMAIL_QUIT_ERROR = -99;

// SMTP standard error code
const int SMTPSERVER_AUTHENTICATIONREQUIRED_ERROR = 530;
const int SMTPSERVER_AUTHENTICATIONTOOWEAK_ERROR = 534;
const int SMTPSERVER_CREDENTIALSINVALID_ERROR = 535;
const int SMTPSERVER_ENCRYPTIONREQUIREDFORAUTH_ERROR = 538;

// SMTP non standard error code
const int SMTPSERVER_AUTHENTICATION_UNSUCCESSFUL_GMAIL_ERROR = 334;

#endif
