#ifndef SMTPSERVERSTATUSCODES_H
#define SMTPSERVERSTATUSCODES_H

const int STATUS_CODE_SERVICE_READY = 220;
const int STATUS_CODE_AUTHENTICATION_SUCCEEDED = 235;
const int STATUS_CODE_REQUESTED_MAIL_ACTION_OK_OR_COMPLETED = 250;
const int STATUS_CODE_SERVER_CHALLENGE = 334;
const int STATUS_CODE_START_MAIL_INPUT = 354;

#endif