//Authenticate error codes
#define CLIENT_AUTHENTICATE_ERROR                           (-81)
#define CLIENT_AUTHENTICATE_TIMEOUT                         (-82)
#define CLIENT_AUTHENTICATE_NONEED                          (-83)
#define CLIENT_AUTHENTICATION_METHOD_NOTSUPPORTED           (-84)

//Send Mail error codes
#define CLIENT_SENDMAIL_MAILFROM_ERROR          (-85)
#define CLIENT_SENDMAIL_MAILFROM_TIMEOUT        (-86)
#define CLIENT_SENDMAIL_RCPTTO_ERROR            (-87)
#define CLIENT_SENDMAIL_RCPTTO_TIMEOUT          (-88)
#define CLIENT_SENDMAIL_DATA_ERROR              (-89)
#define CLIENT_SENDMAIL_DATA_TIMEOUT            (-90)
#define CLIENT_SENDMAIL_HEADERFROM_ERROR        (-91)
#define CLIENT_SENDMAIL_HEADERTOANDCC_ERROR     (-92)
#define CLIENT_SENDMAIL_HEADERSUBJECT_ERROR     (-93)
#define CLIENT_SENDMAIL_HEADERCONTENTTYPE_ERROR (-94)
#define CLIENT_SENDMAIL_BODYPART_ERROR          (-95)
#define CLIENT_SENDMAIL_BODY_ERROR              (-96)
#define CLIENT_SENDMAIL_END_DATA_ERROR          (-97)
#define CLIENT_SENDMAIL_END_DATA_TIMEOUT        (-98)
#define CLIENT_SENDMAIL_QUIT_ERROR              (-99)
