#pragma once

//Init Session error codes
#define SOCKET_INIT_SESSION_CONNECT_ERROR   -1;
#define SOCKET_INIT_SESSION_CONNECT_TIMEOUT   -2;

//Init Client error codes
#define SOCKET_INIT_CLIENT_SEND_EHLO_ERROR   -1;
#define SOCKET_INIT_CLIENT_SEND_EHLO_TIMEOUT   -2;

//Init TLS error codes
#define SOCKET_INIT_CLIENT_SEND_STARTTLS_ERROR   -1;
#define SOCKET_INIT_CLIENT_SEND_STARTTLS_TIMEOUT   -2;