#pragma once

#define SSL_CLIENT_STARTTLS_INITSSLCTX_ERROR                -1;
#define SSL_CLIENT_STARTTLS_BIONEWSSLCONNECT_ERROR          -2;
#define SSL_CLIENT_STARTTLS_CTX_LOAD_VERIFY_LOCATIONS_ERROR -3;
#define SSL_CLIENT_STARTTLS_BIO_CONNECT_ERROR -4;
#define SSL_CLIENT_STARTTLS_BIO_HANDSHAKE_ERROR -5;
#define SSL_CLIENT_STARTTLS_GET_CERTIFICATE_ERROR -6;
#define SSL_CLIENT_STARTTLS_VERIFY_RESULT_ERROR -7;

//Init Session error codes
#define SSL_CLIENT_INITSECURECLIENT_ERROR   -1;
#define SSL_CLIENT_INITSECURECLIENT_TIMEOUT -2;